# -*- coding: utf-8 -*-
"""l_1_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UPyhPcSxXTNnEW360o2dUzopPXDeGV-D

Вывести значение перменной
"""

# Небольшая функция для вывода типа переменной и ее значения
def printFunc(type_value, value):
  print(type_value,": ",value)

#Подаю в функцию тип и значение переменной 
printFunc("Целое число", 123)
printFunc("Текст", "Миша, будешь моим другом?")