# -*- coding: utf-8 -*-
"""l_1_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UPyhPcSxXTNnEW360o2dUzopPXDeGV-D
"""

'''
Знакомство с условным оператором.
Проверка четности. 
'''
num = int(input("Введите целолое число: "))
if num%2==0:
  print("Вы ввели четное число")
else:
  print("Вы ввели нечетное число")